# Copyright (c) 2021-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

version: 2

registries:
  github-privacyguides:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.REPO_PAT}}

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jonaharagon"
    reviewers:
      - "jonaharagon"
    labels:
      - "fix:github_actions"

  # Maintain submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    registries:
      - github-privacyguides
    schedule:
      interval: "monthly"
    labels:
      - "fix:submodules"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
# Disabled because some updates tend to remove needed dependencies for some reason

#  # Maintain dependencies for pipenv
#  - package-ecosystem: "pip"
#    directory: "/"
#    insecure-external-code-execution: allow
#    registries:
#      - github-privacyguides
#    schedule:
#      interval: "daily"
#    assignees:
#      - "jonaharagon"
#    reviewers:
#      - "jonaharagon"
#    labels:
#      - "fix:python"
