# Copyright (c) 2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: "Content Correction"
description: Report any inaccurate, incorrect, or outdated information on the website.
labels: ["t:correction"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting verifiable issues with our website.
        If you simply disagree with an opinion on the website, please open a discussion [on our forum](https://discuss.privacyguides.net) instead.

  - type: input
    attributes:
      label: Affected page
      description: Please let us know which page the incorrect information can be found on.
      placeholder: "https://www.privacyguides.org/en/data-redaction"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please let us know what should be fixed.
      placeholder: The Google Play Store link for ExifEraser is broken...
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Sources
      description: Please provide reliable sources that support the change you are requesting.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I am reporting something that is verifiably incorrect, not a suggestion or opinion.
          required: true
        - label: I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).
          required: true
